import os

THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
database_location = os.path.join(THIS_FOLDER, 'database.db')
UPLOAD_FOLDER = os.path.join(THIS_FOLDER,'static/uploads')
HOME_CAROUSEL_FOLDER = os.path.join(THIS_FOLDER, 'static/images/Homepage')
DOCTOR_FOLDER = os.path.join(THIS_FOLDER, 'static/images/doctors')
SPECIALTY_FOLDER = os.path.join(THIS_FOLDER, 'static/images/illustrations/specialty')
DISEASES_FOLDER = os.path.join(THIS_FOLDER, 'static/images/disease')
DISEASES_ILLUSTRATION_FOLDER = os.path.join(THIS_FOLDER, 'static/images/illustrations/diseases')
VIRTUAL_TOUR_FOLDER = os.path.join(THIS_FOLDER, 'static/images/virtual_tour')
AWARDS_FOLDER = os.path.join(THIS_FOLDER, 'static/images/awards')
HEAD_NEWS_FOLDER = os.path.join(THIS_FOLDER, 'static/images/news/head_news')
NEWS_FOLDER = os.path.join(THIS_FOLDER, 'static/images/news')
BLOGS_FOLDER = os.path.join(THIS_FOLDER, 'static/images/blogs')
TESTIMONIALS_FOLDER = os.path.join(THIS_FOLDER, 'static/images/testimonial')
APPOINTMENT_REPORTS = os.path.join(THIS_FOLDER, 'static/appointment_reports')